pipeline {
    agent {
        docker { 
            image 'maven:3.8.5-openjdk-11'  // Using a proper Maven Docker image
            args '--network=host' // Optional: Allows Docker networking
        } 
    }
    environment {
        DOCKER_HOST = "tcp://192.168.122.5:2375" // Define remote Docker daemon
    }
      stages {
            stage('Init') {
                  steps {
                        echo 'Hi, this is Anshul from LevelUp360'
                        echo 'We are Starting the Testing'
                  }
            }
            stage('Build') {
                  steps {
                        echo 'Building Sample Maven Project'
                  }
            }
            stage('Deploy') {
                  steps {
                        echo "Deploying in Staging Area"
                  }
            }
            stage('Deploy Production') {
                  steps {
                        echo "Deploying in Production Area"
                  }
            }
      }
}
