pipeline {
    agent any

    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image') {
            steps {
                sh "pwd"
                sh "ls -a"
                sh "docker build -t tomcatsamplewebapp:${env.BUILD_ID} -t tomcatsamplewebapp:latest ./java-tomcat-sample-docker"
            }
        }

        steps {
                withCredentials([string(credentialsId: 'docker-hub-credentials', variable: 'DOCKER_PASS')]) {
                    sh "echo $DOCKER_PASS | docker login -u your-docker-username --password-stdin"
                    sh "docker tag tomcatsamplewebapp:${env.BUILD_ID} your-docker-username/tomcatsamplewebapp:${env.BUILD_ID}"
                    sh "docker push your-docker-username/tomcatsamplewebapp:${env.BUILD_ID}"
                    sh "docker push your-docker-username/tomcatsamplewebapp:latest"
                }
        }
    }
}
